# Generated by Django 3.1.5 on 2021-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVP', '0005_auto_20210128_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandasdepecas',
            name='status',
        ),
        migrations.AddField(
            model_name='demandasdepecas',
            name='statusdemanda',
            field=models.BooleanField(default=False, verbose_name='A demanda está finalizada?'),
        ),
    ]
